# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: false
cache: packages
apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev
 - libcurl3
 - libsodium-dev